# Welcome to Jekyll!
#

# Site settings
title: BioDataFrames
description: Big data analytics for molecular biology
owner: BioDataFrames.org
first_published: 2016
email: andreas.prlic@gmail.com

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
whitelist:
  - jekyll-sitemap
  - jekyll-redirect-from
sitemap: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: page
